services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /d/CodeLib/GithubCodes/CS4ACNER/data/kg:/var/lib/neo4j/import
      - /d/CodeLib/GithubCodes/CS4ACNER/data/plugins:/var/lib/neo4j/plugins
      - /d/CodeLib/GithubCodes/CS4ACNER/data/conf:/var/lib/neo4j/conf
    environment:
      NEO4J_AUTH: neo4j/password
#  backend:
#    build:
#      context: ./backend
#    ports:
#      - "8000:8000"
#    depends_on:
#      - neo4j
#    environment:
#      - NEO4J_HOST=neo4j
#      - NEO4J_PORT=7687
#      - NEO4J_USER=neo4j
#      - NEO4J_PASSWORD=password
#
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#
#  ner:
#    image: ner-service:v1
#    ports: ["8001:8000"]
#
#  llm-api:
#    image: llm-gateway:v2
#    environment:
#      OPENAI_KEY: ${SECRET_KEY}